/*
 * generated by Xtext
 */
package org.kermeta.language.sample.logo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LogoTextualSyntaxUiModule extends org.kermeta.language.sample.logo.ui.AbstractLogoTextualSyntaxUiModule {
	public LogoTextualSyntaxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
