<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftm"
    nsURI="http://ftm" nsPrefix="ftm">
  <eSubpackages name="structure" nsPrefix="structure">
    <eClassifiers xsi:type="ecore:EClass" name="ModelingUnit" eSuperTypes="#//structure/TypeDefinitionContainer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Before normalization, for support of concrete syntax, a ModelingUnit can directly own TypeDefinition (ClassDefintion, ModelType, enumeration, ...)&#xD;&#xA;However, this suppose that a package is specified in the namespacePrefix."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
          eType="#//structure/Package" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="root packages contained by this ModelingUnit"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespacePrefix" eType="#//structure/String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The namespacePrefix is used to capture syntax shortcut for creating NamedElement (ModelDefinition, Package, ClassDefinition, ...) in the ModelingUnit.&#xD;&#xA;The normalization process will replace the namespacePrefix by its equivalent NamedElement for all its declared elements."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDefinitionContainer"/>
  </eSubpackages>
</ecore:EPackage>
