<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftm">
  <eSubpackages name="structure">
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Base class definition for the &lt;b>use&lt;/b> of a type."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedType" eSuperTypes="#//structure/Type #//structure/Unresolved">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Special type reference which is still unresolved.&#xD;&#xA;The reference string is used to create a real Type that points to the correct TypeDefinition"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeIdentifier" eType="#//structure/String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String that identifies the Type.&#xD;&#xA;The container of the UnresolvedType  is considered as the context."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usings" eType="#//structure/Using"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="List of Using that can be used to complement the indentifer and resolve this UnresolvedType"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EClass" name="Unresolved" abstract="true" eSuperTypes="#//structure/Object">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Definitions that inherits from this are proxies to the real element they should point to.&#xD;&#xA;A Definition that inherit from Unresolved must also inherit from the Definition it is supposed to replace.&#xD;&#xA;Those definitions should be present only in Unresolved models.&#xD;&#xA; In resolved models they should be replaced by their alternative."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractProperty" abstract="true"
        eSuperTypes="#//structure/Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//structure/AbstractProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedUnresolvedProperties"
          upperBound="-1" eType="#//structure/UnresolvedProperty" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedProperty" eSuperTypes="#//structure/AbstractProperty #//structure/Unresolved">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyIdentifier" eType="#//structure/String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String that identifies the Property.&#xD;&#xA;The container of the UnresolvedProperty  is considered as the context."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractOperation" abstract="true"
        eSuperTypes="#//structure/Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnresolvedOperation" eSuperTypes="#//structure/AbstractOperation #//structure/Unresolved">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationIdentifier"
          eType="#//structure/String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String that identifies the Operation.&#xD;&#xA;The container of the UnresolvedOperation  is considered as the context."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//structure/AbstractOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedUnresolvedOperations"
          upperBound="-1" eType="#//structure/UnresolvedOperation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Using" eSuperTypes="#//structure/Object">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Using is a part of QualifiedName that can be used to complement the indentifer and resolve a given Unresolved object"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="#//structure/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object"/>
  </eSubpackages>
</ecore:EPackage>
