/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.exceptions.validation;

import kermeta.language.structure.Constraint;

/**
 * A sample validator interface for {@link kermeta.exceptions.ConstraintViolatedException}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintViolatedExceptionValidator {
	boolean validate();

	boolean validateConstraintAppliedTo(kermeta.language.structure.Object value);

	boolean validateFailedConstraint(Constraint value);
}
