/*
 * generated by Xtext
 */
package org.kermeta.language.sample.logo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogoTextualSyntaxRuntimeModule extends org.kermeta.language.sample.logo.AbstractLogoTextualSyntaxRuntimeModule {

}
