/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.kermeta.language.emftexteditor.mopp;

// A CodeCompletionHelper can be used to derive completion proposals for partial
// documents. It runs the parser generated by EMFText in a special mode (i.e., the
// rememberExpectedElements mode). Based on the elements that are expected by the
// parser for different regions in the document, valid proposals are computed.
public class KermetaCodeCompletionHelper {
	
	// Computes a set of proposals for the given document assuming the cursor is
	// at 'cursorOffset'. The proposals are derived using the meta information, i.e.,
	// the generated language plug-in.
	//
	// @param metaInformation
	// @param content the documents content
	// @param cursorOffset
	// @return
	public org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal[] computeCompletionProposals(org.kermeta.language.emftexteditor.IKermetaTextResource originalResource, String content, int cursorOffset) {
		org.eclipse.emf.ecore.resource.ResourceSet resourceSet = new org.eclipse.emf.ecore.resource.impl.ResourceSetImpl();
		// the shadow resource needs the same URI because reference resolvers may use the URI to resolve external references
		org.kermeta.language.emftexteditor.IKermetaTextResource resource = (org.kermeta.language.emftexteditor.IKermetaTextResource) resourceSet.createResource(originalResource.getURI());
		java.io.ByteArrayInputStream inputStream = new java.io.ByteArrayInputStream(content.getBytes());
		org.kermeta.language.emftexteditor.mopp.KermetaMetaInformation metaInformation = resource.getMetaInformation();
		org.kermeta.language.emftexteditor.IKermetaTextParser parser = metaInformation.createParser(inputStream, null);
		org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[] expectedElements = parseToExpectedElements(parser, resource);
		if (expectedElements == null) {
			return new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal[0];
		}
		if (expectedElements.length == 0) {
			return new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal[0];
		}
		java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedAfterCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset));
		java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedBeforeCursor = java.util.Arrays.asList(getElementsExpectedAt(expectedElements, cursorOffset - 1));
		setPrefixes(expectedAfterCursor, content, cursorOffset);
		setPrefixes(expectedBeforeCursor, content, cursorOffset);
		// first we derive all possible proposals from the set of elements that are expected at the cursor position
		java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> allProposals = new java.util.LinkedHashSet<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>();
		java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> rightProposals = deriveProposals(expectedAfterCursor, content, resource, cursorOffset);
		java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> leftProposals = deriveProposals(expectedBeforeCursor, content, resource, cursorOffset);
		// second, the set of left proposals (i.e., the ones before the cursor) is
		// checked for emptiness. if the set is empty, the right proposals (i.e., 
		// the ones after the cursor are removed, because it does not make sense to
		// propose them until the element before the cursor was completed
		allProposals.addAll(leftProposals);
		if (leftProposals.isEmpty()) {
			allProposals.addAll(rightProposals);
		}
		// third, the proposals are sorted according to their relevance
		// proposals that matched the prefix are preferred over ones that did not
		// afterward proposals are sorted alphabetically
		final java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> sortedProposals = new java.util.ArrayList<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>(allProposals);
		java.util.Collections.sort(sortedProposals);
		return sortedProposals.toArray(new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal[sortedProposals.size()]);
	}
	
	public org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[] parseToExpectedElements(org.kermeta.language.emftexteditor.IKermetaTextParser parser, org.kermeta.language.emftexteditor.IKermetaTextResource resource) {
		final java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedElements = parser.parseToExpectedElements(null, resource);
		if (expectedElements == null) {
			return new org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[0];
		}
		removeDuplicateEntries(expectedElements);
		removeInvalidEntriesAtEnd(expectedElements);
		return expectedElements.toArray(new org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[expectedElements.size()]);
	}
	
	private void removeDuplicateEntries(java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedElements) {
		for (int i = 0; i < expectedElements.size() - 1; i++) {
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal elementAtIndex = expectedElements.get(i);
			for (int j = i + 1; j < expectedElements.size();) {
				org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal elementAtNext = expectedElements.get(j);
				if (elementAtIndex.equals(elementAtNext) && elementAtIndex.getStartExcludingHiddenTokens() == elementAtNext.getStartExcludingHiddenTokens()) {
					expectedElements.remove(j);
				} else {
					j++;
				}
			}
		}
	}
	
	private void removeInvalidEntriesAtEnd(java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedElements) {
		for (int i = 0; i < expectedElements.size() - 1;) {
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal elementAtIndex = expectedElements.get(i);
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal elementAtNext = expectedElements.get(i + 1);
			if (elementAtIndex.getStartExcludingHiddenTokens() == elementAtNext.getStartExcludingHiddenTokens() && shouldRemove(elementAtIndex.getFollowSetID(), elementAtNext.getFollowSetID())) {
				expectedElements.remove(i + 1);
			} else {
				i++;
			}
		}
	}
	
	public boolean shouldRemove(int followSetID1, int followSetID2) {
		return followSetID1 != followSetID2;
	}
	
	private String findPrefix(java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedElements, org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedAtCursor, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return "";
		}
		int end = 0;
		for (org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedElement : expectedElements) {
			if (expectedElement == expectedAtCursor) {
				final int start = expectedElement.getStartExcludingHiddenTokens();
				if (start >= 0  && start < Integer.MAX_VALUE) {
					end = start;
				}
				break;
			}
		}
		end = Math.min(end, cursorOffset);
		final String prefix = content.substring(end, Math.min(content.length(), cursorOffset));
		return prefix;
	}
	
	private java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> deriveProposals(java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedElements, String content, org.kermeta.language.emftexteditor.IKermetaTextResource resource, int cursorOffset) {
		java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> resultSet = new java.util.HashSet<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>();
		for (org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedElement : expectedElements) {
			resultSet.addAll(deriveProposals(expectedElement, content, resource, cursorOffset));
		}
		return resultSet;
	}
	
	private java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> deriveProposals(org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedTerminal, String content, org.kermeta.language.emftexteditor.IKermetaTextResource resource, int cursorOffset) {
		org.kermeta.language.emftexteditor.mopp.KermetaMetaInformation metaInformation = resource.getMetaInformation();
		org.kermeta.language.emftexteditor.IKermetaLocationMap locationMap = resource.getLocationMap();
		org.kermeta.language.emftexteditor.IKermetaExpectedElement expectedElement = (org.kermeta.language.emftexteditor.IKermetaExpectedElement) expectedTerminal.getTerminal();
		if (expectedElement instanceof org.kermeta.language.emftexteditor.mopp.KermetaExpectedCsString) {
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedCsString csString = (org.kermeta.language.emftexteditor.mopp.KermetaExpectedCsString) expectedElement;
			return deriveProposal(csString, content, expectedTerminal.getPrefix(), cursorOffset);
		} else if (expectedElement instanceof org.kermeta.language.emftexteditor.mopp.KermetaExpectedStructuralFeature) {
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedStructuralFeature expectedFeature = (org.kermeta.language.emftexteditor.mopp.KermetaExpectedStructuralFeature) expectedElement;
			org.eclipse.emf.ecore.EStructuralFeature feature = expectedFeature.getFeature();
			org.eclipse.emf.ecore.EClassifier featureType = feature.getEType();
			java.util.List<org.eclipse.emf.ecore.EObject> elementsAtCursor = locationMap.getElementsAt(cursorOffset);
			org.eclipse.emf.ecore.EObject container = null;
			// we need to skip the proxy elements at the cursor, because they are not the container for the reference we try to complete
			for (int i = 0; i < elementsAtCursor.size(); i++) {
				container = elementsAtCursor.get(i);
				if (!container.eIsProxy()) {
					break;
				}
			}
			if (feature instanceof org.eclipse.emf.ecore.EReference) {
				org.eclipse.emf.ecore.EReference reference = (org.eclipse.emf.ecore.EReference) feature;
				if (featureType instanceof org.eclipse.emf.ecore.EClass) {
					if (reference.isContainment()) {
						// the FOLLOW set should contain only non-containment references
						assert false;
					} else {
						return handleNCReference(metaInformation, container, reference, expectedTerminal.getPrefix());
					}
				}
			} else if (feature instanceof org.eclipse.emf.ecore.EAttribute) {
				org.eclipse.emf.ecore.EAttribute attribute = (org.eclipse.emf.ecore.EAttribute) feature;
				if (featureType instanceof org.eclipse.emf.ecore.EEnum) {
					org.eclipse.emf.ecore.EEnum enumType = (org.eclipse.emf.ecore.EEnum) featureType;
					return deriveProposals(expectedTerminal, enumType, content, cursorOffset);
				} else {
					// handle EAttributes (derive default value depending on
					// the type of the attribute, figure out token resolver, and
					// call deResolve())
					return handleAttribute(metaInformation, expectedFeature, container, attribute, expectedTerminal.getPrefix());
				}
			} else {
				// there should be no other subclass of EStructuralFeature
				assert false;
			}
		} else {
			// there should be no other class implementing IExpectedElement
			assert false;
		}
		return java.util.Collections.emptyList();
	}
	
	private java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> deriveProposals(org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedElement, org.eclipse.emf.ecore.EEnum enumType, String content, int cursorOffset) {
		java.util.Collection<org.eclipse.emf.ecore.EEnumLiteral> enumLiterals = enumType.getELiterals();
		java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> result = new java.util.HashSet<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>();
		for (org.eclipse.emf.ecore.EEnumLiteral literal : enumLiterals) {
			String proposal = literal.getLiteral();
			String prefix = expectedElement.getPrefix();
			if (matches(proposal, prefix)) {
				result.add(new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal(proposal, prefix, !"".equals(prefix), true));
			}
		}
		return result;
	}
	
	private java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> handleNCReference(org.kermeta.language.emftexteditor.mopp.KermetaMetaInformation metaInformation, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EReference reference, java.lang.String prefix) {
		// proposals for non-containment references are derived by calling the
		// reference resolver switch in fuzzy mode.
		org.kermeta.language.emftexteditor.IKermetaReferenceResolverSwitch resolverSwitch = metaInformation.getReferenceResolverSwitch();
		org.kermeta.language.emftexteditor.IKermetaReferenceResolveResult<org.eclipse.emf.ecore.EObject> result = new org.kermeta.language.emftexteditor.mopp.KermetaReferenceResolveResult<org.eclipse.emf.ecore.EObject>(true);
		resolverSwitch.resolveFuzzy(prefix, container, reference, 0, result);
		java.util.Collection<org.kermeta.language.emftexteditor.IKermetaReferenceMapping<org.eclipse.emf.ecore.EObject>> mappings = result.getMappings();
		if (mappings != null) {
			java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> resultSet = new java.util.HashSet<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>();
			for (org.kermeta.language.emftexteditor.IKermetaReferenceMapping<org.eclipse.emf.ecore.EObject> mapping : mappings) {
				final String identifier = mapping.getIdentifier();
				// the proposal can be added without checking the prefix because this is
				// performed by the reference resolvers
				resultSet.add(new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal(identifier, prefix, true, true));
			}
			return resultSet;
		}
		return java.util.Collections.emptyList();
	}
	
	private java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> handleAttribute(org.kermeta.language.emftexteditor.mopp.KermetaMetaInformation metaInformation, org.kermeta.language.emftexteditor.mopp.KermetaExpectedStructuralFeature expectedFeature, org.eclipse.emf.ecore.EObject container, org.eclipse.emf.ecore.EAttribute attribute, java.lang.String prefix) {
		java.lang.Object defaultValue = getDefaultValue(attribute);
		if (defaultValue != null) {
			org.kermeta.language.emftexteditor.IKermetaTokenResolverFactory tokenResolverFactory = metaInformation.getTokenResolverFactory();
			String tokenName = expectedFeature.getTokenName();
			if (tokenName != null) {
				org.kermeta.language.emftexteditor.IKermetaTokenResolver tokenResolver = tokenResolverFactory.createTokenResolver(tokenName);
				if (tokenResolver != null) {
					String defaultValueAsString = tokenResolver.deResolve(defaultValue, attribute, container);
					java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> resultSet = new java.util.HashSet<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>();
					if (matches(defaultValueAsString, prefix)) {
						resultSet.add(new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal(defaultValueAsString, prefix, !"".equals(prefix), true));
					}
					return resultSet;
				}
			}
		}
		return java.util.Collections.emptyList();
	}
	
	private java.lang.Object getDefaultValue(org.eclipse.emf.ecore.EAttribute attribute) {
		String typeName = attribute.getEType().getName();
		if ("EString".equals(typeName)) {
			return "some" + org.kermeta.language.emftexteditor.util.KermetaStringUtil.capitalize(attribute.getName());
		}
		return attribute.getDefaultValue();
	}
	
	private java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> deriveProposal(org.kermeta.language.emftexteditor.mopp.KermetaExpectedCsString csString, String content, String prefix, int cursorOffset) {
		String proposal = csString.getValue();
		java.util.Collection<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal> result = new java.util.HashSet<org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal>();
		if (matches(proposal, prefix)) {
			result.add(new org.kermeta.language.emftexteditor.mopp.KermetaCompletionProposal(proposal, prefix, !"".equals(prefix), false));
		}
		return result;
	}
	
	// for each given expected elements the prefix is calculated
	// the prefix depends on the current document content, the cursor position, and
	// the position where the element is expected
	private void setPrefixes(java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedElements, String content, int cursorOffset) {
		if (cursorOffset < 0) {
			return;
		}
		for (org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedElement : expectedElements) {
			java.lang.String prefix = findPrefix(expectedElements, expectedElement, content, cursorOffset);
			expectedElement.setPrefix(prefix);
		}
	}
	
	public org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[] getElementsExpectedAt(org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[] allExpectedElements, int cursorOffset) {
		java.util.List<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal> expectedAtCursor = new java.util.ArrayList<org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal>();
		for (int i = 0; i < allExpectedElements.length; i++) {
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal expectedElement = allExpectedElements[i];
			int startIncludingHidden = expectedElement.getStartIncludingHiddenTokens();
			int end = getEnd(allExpectedElements, i);
			if (cursorOffset >= startIncludingHidden && cursorOffset <= end) {
				expectedAtCursor.add(expectedElement);
			}
		}
		return expectedAtCursor.toArray(new org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[expectedAtCursor.size()]);
	}
	
	private int getEnd(org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal[] allExpectedElements, int indexInList) {
		org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal elementAtIndex = allExpectedElements[indexInList];
		int startIncludingHidden = elementAtIndex.getStartIncludingHiddenTokens();
		int startExcludingHidden = elementAtIndex.getStartExcludingHiddenTokens();
		for (int i = indexInList + 1; i < allExpectedElements.length; i++) {
			org.kermeta.language.emftexteditor.mopp.KermetaExpectedTerminal elementAtI = allExpectedElements[i];
			int startIncludingHiddenForI = elementAtI.getStartIncludingHiddenTokens();
			int startExcludingHiddenForI = elementAtI.getStartExcludingHiddenTokens();
			if (startIncludingHidden != startIncludingHiddenForI || startExcludingHidden != startExcludingHiddenForI) {
				return startIncludingHiddenForI - 1;
			}
		}
		return Integer.MAX_VALUE;
	}
	
	private boolean matches(java.lang.String proposal, java.lang.String prefix) {
		return (proposal.startsWith(prefix) || org.kermeta.language.emftexteditor.util.KermetaStringUtil.matchCamelCase(prefix, proposal) != null) && !proposal.equals(prefix);
	}
	
}
