/*
* generated by Xtext
*/
package org.kermeta.language.sample.logo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LogoTextualSyntaxOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
