/*
 * generated by Xtext
 */
package org.kermeta.language.sample.logo.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.kermeta.language.sample.logo.ui.internal.LogoTextualSyntaxActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogoTextualSyntaxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LogoTextualSyntaxActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LogoTextualSyntaxActivator.getInstance().getInjector(LogoTextualSyntaxActivator.ORG_KERMETA_LANGUAGE_SAMPLE_LOGO_LOGOTEXTUALSYNTAX);
	}
	
}
