/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.language.behavior.validation;

import kermeta.language.behavior.CallExpression;
import kermeta.language.behavior.Expression;

/**
 * A sample validator interface for {@link kermeta.language.behavior.Assignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssignmentValidator {
	boolean validate();

	boolean validateValue(Expression value);

	boolean validateTarget(CallExpression value);

	boolean validateIsCast(Boolean value);
}
