/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.language.structure.validation;

import kermeta.language.structure.Property;

/**
 * A sample validator interface for {@link kermeta.language.structure.PropertyConstraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyConstraintValidator {
	boolean validate();

	boolean validateProperty(Property value);
}
