/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.ecore.validation;

/**
 * A sample validator interface for {@link kermeta.ecore.EFeatureMapEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EFeatureMapEntryValidator {
	boolean validate();

	boolean validateValue(kermeta.language.structure.Object value);

	boolean validateEStructuralFeatureName(String value);
}
