/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.language.behavior.validation;

import kermeta.language.behavior.Expression;

/**
 * A sample validator interface for {@link kermeta.language.behavior.Loop}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopValidator {
	boolean validate();

	boolean validateInitialization(Expression value);

	boolean validateBody(Expression value);

	boolean validateStopCondition(Expression value);
}
