/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.exceptions.validation;

import kermeta.exceptions.ConstraintViolatedInv;

import kermeta.standard.Bag;

/**
 * A sample validator interface for {@link kermeta.exceptions.ConstraintsDiagnostic}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintsDiagnosticValidator {
	boolean validate();

	boolean validateSetConstraints(Bag<ConstraintViolatedInv> value);
}
