/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.standard.validation;

import java.util.Iterator;

import kermeta.standard.Collection;

/**
 * A sample validator interface for {@link kermeta.standard.Iterator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IteratorValidator {
	boolean validate();

	boolean validateJavaIterator(Iterator<Object> value);

	boolean validateKermetaCollection(Collection<Object> value);
}
