/*
* generated by Xtext
*/
package org.kermeta.language.sample.logo.ui.contentassist;

import org.kermeta.language.sample.logo.ui.contentassist.AbstractLogoTextualSyntaxProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LogoTextualSyntaxProposalProvider extends AbstractLogoTextualSyntaxProposalProvider {

}
