/*
* generated by Xtext
*/
package org.kermeta.language.sample.logo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LogoTextualSyntaxAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/kermeta/language/sample/logo/parser/antlr/internal/InternalLogoTextualSyntax.tokens");
	}
}
