/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.utils.validation;

import java.util.Hashtable;

/**
 * A sample validator interface for {@link kermeta.utils.Hashtable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HashtableValidator {
	boolean validate();

	boolean validateWrappedHashtable(Hashtable<Object, Object> value);
}
