/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kermeta.language.structure.validation;

import kermeta.language.structure.Tag;

import kermeta.persistence.Resource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kermeta.language.structure.Object}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ObjectValidator {
	boolean validate();

	boolean validateTag(EList<Tag> value);

	boolean validateOwnedTags(EList<Tag> value);

	boolean validateOid(Integer value);

	boolean validateInternalContainingResource(Resource value);
}
